module scaiev_glue import ariane_pkg::*;
   #(
    parameter config_pkg::cva6_cfg_t CVA6Cfg = config_pkg::cva6_cfg_empty,
    parameter INSTRQUEUE_ID_WIDTH = 1,
    parameter type scaiev_instr_decoded_t = logic,
    parameter type scaiev_id_pipeinto_t = logic
    )

    (
        input logic clk,
        input logic rst,

        input logic [CVA6Cfg.XLEN-1:0] scaiev_fetch_PC,
        input logic scaiev_fetch_isStalling,
        input logic scaiev_fetch_isFlushing,
        input logic scaiev_fetch_isReplaying,
        output logic scaiev_fetch_ignoreReplay,
        input logic [CVA6Cfg.INSTR_PER_FETCH-1:0] scaiev_realign_isValid,
        input logic [CVA6Cfg.INSTR_PER_FETCH-1:0][31:0] scaiev_realign_rdInstr,
        input logic [CVA6Cfg.INSTR_PER_FETCH-1:0][CVA6Cfg.XLEN-1:0] scaiev_realign_PC,
        input logic [CVA6Cfg.INSTR_PER_FETCH-1:0] scaiev_realign_isStalling,
        input logic scaiev_realign_isFlushing,
        input logic [1:0] scaiev_fetch_reqID,
        input logic [1:0] scaiev_realign_reqID,
        input logic [1:0] scaiev_fetch_reqID_flushFrom,
        input logic [2:0] scaiev_fetch_reqID_flushCount,
        input logic [CVA6Cfg.INSTR_PER_FETCH-1:0][INSTRQUEUE_ID_WIDTH-1:0] scaiev_realign_instrqueueID,
        input logic scaiev_realign_fully_unaligned,
        input logic [CVA6Cfg.NrIssuePorts-1:0][INSTRQUEUE_ID_WIDTH-1:0] scaiev_decode_instrqueueID,
        output logic [CVA6Cfg.XLEN-1:0] scaiev_decode_pcOverride,
        output logic scaiev_decode_pcOverride_valid,
        input logic scaiev_decode_isFlushing,
        input logic [CVA6Cfg.NrIssuePorts-1:0] scaiev_decode_isStalling,
        output logic [CVA6Cfg.NrIssuePorts-1:0] scaiev_decode_stall,
        input logic [CVA6Cfg.NrIssuePorts-1:0] scaiev_decode_isValid,
        input logic [CVA6Cfg.NrIssuePorts-1:0][31:0] scaiev_decode_rdInstr,
        input scaiev_instr_decoded_t [CVA6Cfg.NrIssuePorts-1:0] scaiev_decode_decInstr,
        input scaiev_id_pipeinto_t scaiev_id_pipeinto,
        input logic scaiev_issue_isFlushing,
        input logic [CVA6Cfg.NrIssuePorts-1:0] scaiev_issue_isStalling,
        input logic [CVA6Cfg.NrIssuePorts-1:0] scaiev_issue_isValid,
        input logic [CVA6Cfg.NrIssuePorts-1:0] scaiev_issue_pipeinto_scaievfu,
        input logic [CVA6Cfg.NrIssuePorts-1:0][CVA6Cfg.XLEN-1:0] scaiev_issue_rdRS1,
        input logic [CVA6Cfg.NrIssuePorts-1:0][riscv::XLEN-1:0] scaiev_issue_rdRS2,
        input logic [CVA6Cfg.NrIssuePorts-1:0][31:0] scaiev_issue_rdInstr,
        input logic [CVA6Cfg.NrIssuePorts-1:0][riscv::XLEN-1:0] scaiev_issue_PC,
        input logic [CVA6Cfg.NrIssuePorts-1:0][CVA6Cfg.TRANS_ID_BITS-1:0] scaiev_issue_trans_id_o,

        input logic scaiev_scoreboard_isFlushing,
        input logic scaiev_execute_isFlushing,
        input logic scaiev_execute_isNew,
        input logic scaiev_execute_isValid,
        input logic scaiev_execute_isStalling,
        output logic scaiev_execute_stall,
        output logic scaiev_execute_hasWriteback,

        output logic scaiev_execute_semicoupled_deq,
        output logic scaiev_execute_semicoupled_reenq,
        input logic [31:0] scaiev_execute_rdInstr,
        input logic [CVA6Cfg.XLEN-1:0] scaiev_execute_rdRS1,
        input logic [CVA6Cfg.XLEN-1:0] scaiev_execute_rdRS2,
        input logic [CVA6Cfg.TRANS_ID_BITS-1:0] scaiev_execute_trans_id_o,
        input logic [CVA6Cfg.XLEN-1:0] scaiev_execute_rdMem_result,
        input logic scaiev_execute_rdMem_result_valid,
        input logic [CVA6Cfg.TRANS_ID_BITS-1:0] scaiev_execute_rdMem_result_trans_id,
        input logic scaiev_execute_rdMem_result_has_trans_id,
        input logic [CVA6Cfg.NrCommitPorts-1:0] scaiev_commit_trans_id_valid,
        input logic [CVA6Cfg.NrCommitPorts-1:0] scaiev_commit_drop,
        input logic [CVA6Cfg.NrCommitPorts-1:0][CVA6Cfg.TRANS_ID_BITS-1:0] scaiev_commit_trans_id,
        input logic [CVA6Cfg.NrCommitPorts-1:0][CVA6Cfg.XLEN-1:0] scaiev_commit_PC,

        output logic [CVA6Cfg.XLEN-1:0] scaiev_fetch_wrPC,
        output logic scaiev_fetch_wrPCValid,
        output logic scaiev_fetch_stall,
        output logic scaiev_realign_isBranch,
        output logic scaiev_realign_isJump,
        //output logic scaiev_realign_isZOLJump,
        //output logic [63:0] scaiev_realign_jumpAddr,
        output logic scaiev_decode_flush,
        output logic [CVA6Cfg.NrIssuePorts-1:0] scaiev_decode_isSCAIEV,
        output logic [CVA6Cfg.NrIssuePorts-1:0] scaiev_decode_isSCAIEV_hasRS1,
        output logic [CVA6Cfg.NrIssuePorts-1:0] scaiev_decode_isSCAIEV_hasRS2,
        output logic [CVA6Cfg.NrIssuePorts-1:0] scaiev_decode_isSCAIEV_hasRD,
        output logic [CVA6Cfg.NrIssuePorts-1:0] scaiev_decode_isSCAIEV_hasRD_decoupled,
        output logic [CVA6Cfg.NrIssuePorts-1:0] scaiev_decode_isBranch,
        output logic [CVA6Cfg.NrIssuePorts-1:0] scaiev_decode_isLoad,
        output logic [CVA6Cfg.NrIssuePorts-1:0] scaiev_decode_isStore,
        output logic [CVA6Cfg.NrIssuePorts-1:0] scaiev_issue_stall,
        output logic scaiev_issue_flush,
        output logic [CVA6Cfg.NrIssuePorts-1:0] scaiev_issue_mem_stall,
        output logic scaiev_execute_wrRD_valid,
        output logic scaiev_execute_isJump,
        input logic scaiev_execute_mem_ready,
        input logic scaiev_execute_lsuvalid, //regular LSU op in Execute
        output logic scaiev_execute_rdMem_valid,
        output logic scaiev_execute_wrMem_valid,
        output logic [CVA6Cfg.XLEN-1:0] scaiev_execute_jumpAddress,
        output logic [CVA6Cfg.XLEN-1:0] scaiev_execute_wrRD,
        output logic [CVA6Cfg.TRANS_ID_BITS-1:0] scaiev_execute_trans_id_i,
        output logic scaiev_execute_isBranch,
        output logic scaiev_execute_branch_isTaken,
        output logic [CVA6Cfg.XLEN-1:0] scaiev_execute_wrMem,
        output logic [CVA6Cfg.XLEN-1:0] scaiev_execute_memAddr,
        output logic [2:0] scaiev_execute_memSize,
        output logic scaiev_execute_memAddr_valid,
        output logic scaiev_execute_wrMem_suppress_wb,
        output logic scaiev_execute_mem_has_trans_id,
        output logic [CVA6Cfg.TRANS_ID_BITS-1:0] scaiev_execute_mem_trans_id,

        output logic scaiev_writeback_spawn_valid,
        output logic [CVA6Cfg.XLEN-1:0] scaiev_writeback_spawn_data,
        output logic [4:0] scaiev_writeback_spawn_addr
    );

endmodule
